### ISSUE TITLE
Use memcached on Heroku

### ISSUE THREAD

**Issue by sbaer** [mcneel/compute.rhino3d.appserver#39]
Provide an option in our appserver caching to use memcached instead of our current in-memory cache. We would need to include something like the hash of a definition contents in the key so we don't get old cache results from a previous run of the appserver and an old GH definition.

Seems like we could check for a memcached environment variable on Heroku and if it exists use that instead of the in-memory cache.

**Comment by fraguada** [comment]
First test of this here: https://github.com/mcneel/compute.rhino3d.appserver/tree/luis/memcache

**Comment by fraguada** [comment]
- [x] Seems like we could check for a memcached environment variable on Heroku and if it exists use that instead of the in-memory cache.
- [ ] We would need to include something like the hash of a definition contents in the key so we don't get old cache results from a previous run of the appserver and an old GH definition. TODO

**Comment by fraguada** [comment]
fixed in #51
