### ISSUE TITLE
Test appserver locally against a remote compute server

### ISSUE THREAD

**Issue by andrewringler** [mcneel/compute.rhino3d.appserver#63]
I have appserver running fine for production. We have a compute server in a virtual machine and we have appserver on a separate web machine.

For locally testing during development I am trying to run appserver locally, while still connecting to our remote compute server so that I do not have to install Rhino on my local machine. So I am doing:

    export COMPUTE_URL=some external server
    export RHINO_API_TOKEN=…
    export RHINO_COMPUTE_KEY=…
    npm start

But, this does not seem to work, I keep getting 500 errors from the compute server. Should I expect this type of setup to work? Does the compute server require some sort of publicly accessible callback URL at appserver?

Thanks for any thoughts. Andrew.

**Comment by pearswj** [comment]
This kind of set up doesn't work unless the appserver (running on your machine) is also accessible from compute. When the appserver makes a request to compute to solve a grasshopper definition it includes a link to the definition, rather than send the whole file. Compute then downloads the file using the link and will cache the file so that it doesn't need to do this every time. If you're running locally then this link will be something like `http://localhost:3000/definition/<id>`, which isn't accessible from compute.

To get around this you could use something like [ngrok](https://ngrok.com/) (free version is fine). Run `ngrok http 3000` and leave it running at the same time as the appserver is running. Use the unique ngrok.io url that's given to you to access your appserver. This set up should be fine for testing.

p.s. use `RHINO_COMPUTE_URL` and `RHINO_COMPUTE_KEY`. You shouldn't need to set `RHINO_API_TOKEN`.

**Comment by andrewringler** [comment]
Perfect thanks! ngrok worked for me.
